# cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: football-db
spec:
  schedule: "43 17 * * 1"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: football-db
            image: us-central1-docker.pkg.dev/fifa-project-399416/football-db-repo/football-db-gke:latest
            args:
            - /bin/sh
            - -c
            - date;
            - ls;
            - pipenv run python ./scripts/app.py
          restartPolicy: OnFailure